import React, { useState, useRef } from 'react';
import { 
  Sparkles, 
  Upload, 
  Trash2, 
  Copy, 
  CheckCircle2, 
  Zap,
  Info,
  AlertCircle,
  Video,
  UserCircle,
  MessageSquare,
  Type,
  MapPin,
  Clock,
  Mic,
  Activity
} from 'lucide-react';

// Hardcoded API Keys
const MISTRAL_KEY = 'UCNgkoAkHk5ZvJRjy7EI1PjFoZrx8wKw';
const GEMINI_KEYS = [
  'AIzaSyAAMXblFJS_aSrroYDnYZdo4DRT2KHzXu4',
  'AIzaSyByBYVqa9fXqWkw-0AVs3ifFGA8okgw8TM',
  'AIzaSyCC8FhQHyTFhO1-2zFgEQtGy47Yt6ipeyw',
  'AIzaSyAej2ZKvhOtHFTGpePGX3pXedFwkukEyJs'
];

const BLOCO_DE_REALISMO = `Ultra realistic human skin with visible pores, micro skin texture, fine facial hair peach fuzz, natural skin imperfections, realistic eye reflections, natural lip texture, subtle facial asymmetry.
Real smartphone camera recording, slight handheld camera movement, smartphone compression artifacts, sensor noise, natural lighting, no beauty filter, no artificial smoothing, authentic human appearance.`;

const SCREEN_CONSTRAINTS = `Screen constraints:
No cellphone interface elements on screen.
No recording UI.
No battery icon.
No signal icon.
No notification icons.
No app overlays.
No TikTok interface.
No captions generated by the platform.
No floating buttons.
No on-screen camera icons.
Clean video frame only.`;

const PRODUCT_FIDELITY = `Product fidelity is critical.
The product must replicate the reference image exactly with strict geometric fidelity.
Do not redesign, reinterpret, or modify the product in any way.
The shape, geometry, proportions, colors, structure, and number of parts must remain identical to the reference image.
Only the parts visible in the reference image are allowed to exist.
No additional handles.
No extra extensions.
No added plastic parts.
No attachments.
No redesigned shapes.
No invented features.
No modifications to the product structure.
The product must maintain the exact geometry and proportions from the reference image.
If the product contains multiple pieces, the exact number of pieces must remain unchanged.
The product must remain visually identical to the reference object.
Product must occupy at least 50% of the frame to preserve detail accuracy.
The model must prioritize reference image fidelity over creative interpretation.`;

interface UmbraAgentUGCToolProps {
  userTier?: string;
}

const UmbraAgentUGCTool: React.FC<UmbraAgentUGCToolProps> = ({ userTier }) => {
  const [productName, setProductName] = useState('');
  const [productDetails, setProductDetails] = useState('');
  const [imageBase64, setImageBase64] = useState<string | null>(null);
  const [selectedModel, setSelectedModel] = useState<'gemini' | 'mistral'>('gemini');
  const [scriptMode, setScriptMode] = useState<'auto' | 'manual'>('auto');
  const [manualScripts, setManualScripts] = useState({
    scrollStop: 'Gente… olha isso aqui, que eu comprei no tiktok shop',
    curiosidade: '',
    demonstracao: 'O que eu mais gostei foi isso aqui…',
    cta: 'Se você quiser o seu também, clica no carrinho laranja aqui no cantinho da tela antes que acabe.'
  });
  const [sceneLocation, setSceneLocation] = useState('Em uma cozinha moderna');
  const [sceneTime, setSceneTime] = useState('Durante o dia, iluminação natural clara');
  const [characterAction, setCharacterAction] = useState('Segurando o produto próximo à câmera e demonstrando');
  const [microphoneType, setMicrophoneType] = useState('lapela sem fio ou com fio');
  const [isGenerating, setIsGenerating] = useState(false);
  const [prompts, setPrompts] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.size > 5 * 1024 * 1024) {
      setError('⚠️ A imagem deve ter menos de 5MB.');
      return;
    }

    const reader = new FileReader();
    reader.onloadend = () => {
      setImageBase64(reader.result as string);
      setError(null);
    };
    reader.readAsDataURL(file);
  };

  const removeImage = () => {
    setImageBase64(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const callGemini = async (productTitle: string, details: string) => {
    // Rotation logic for Gemini Keys
    let lastError = null;
    for (const apiKey of GEMINI_KEYS) {
      try {
        const parts: any[] = [];
        if (imageBase64) {
          const mimeType = imageBase64.split(';')[0].split(':')[1];
          const base64Data = imageBase64.split(',')[1];
          parts.push({ inline_data: { data: base64Data, mime_type: mimeType } });
        }

        const prompt = `Você é um especialista em marketing de vídeos UGC (User Generated Content) para TikTok.
O usuário quer promover o produto: "${productTitle}"
${details ? `Detalhes do produto: "${details}"` : ''}
Cenas visuais: O vídeo se passa em "${sceneLocation}", no horário "${sceneTime}". O personagem estará "${characterAction}" usando um "${microphoneType}".
${imageBase64 ? 'Use a imagem fornecida para entender melhor o produto e seus benefícios.' : ''}

Gere 3 textos em Português do Brasil para serem falados em um vídeo.
REGRA CRÍTICA: Cada fala gerada deve ter o tamanho ideal para ser falada em até 7 segundos (aproximadamente 15 a 20 palavras).
As falas devem soar extremamente naturais, como uma pessoa real gravando com o celular.
Regras:
- Não repita os mesmos gatilhos mentais.
- Os benefícios na curiosidade e na demonstração DEVEM ser diferentes.

1. descricao_simples: A fala completa do primeiro vídeo. DEVE OBRIGATORIAMENTE começar com a frase exata "Gente… olha isso aqui, que eu comprei no tiktok shop" e em seguida descrever o produto de forma simples e atrativa. (A fala inteira deve dar até 7 segundos).
2. curiosidade_beneficio: Uma fala usando um gatilho mental (ex: escassez, prova social, novidade, curiosidade) seguida de um benefício do produto. (Até 7 segundos de fala).
3. demonstracao_beneficio: A fala completa do terceiro vídeo. DEVE OBRIGATORIAMENTE começar com a frase exata "O que eu mais gostei foi isso aqui…" e focar em um benefício DIFERENTE do anterior. (A fala inteira deve dar até 7 segundos).

Responda APENAS em JSON com as chaves: descricao_simples, curiosidade_beneficio, demonstracao_beneficio.`;

        parts.push({ text: prompt });

        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              contents: [{ parts }],
              generationConfig: {
                responseMimeType: 'application/json',
                temperature: 0.9
              }
            })
          }
        );

        if (!response.ok) {
          const err = await response.json();
          throw new Error(err.error?.message || `Gemini error ${response.status}`);
        }

        const data = await response.json();
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '{}';
        return JSON.parse(text.replace(/```json|```/g, '').trim());
      } catch (e: any) {
        lastError = e;
        console.warn(`Gemini API key failed, trying next...`, e);
      }
    }
    throw lastError || new Error("Falha em todas as chaves Gemini.");
  };

  const callMistral = async (productTitle: string, details: string) => {
    const systemPrompt = `Você é um especialista em marketing de vídeos UGC para TikTok. Responda APENAS com JSON válido, sem markdown, sem texto extra.`;

    const userPrompt = `Produto: "${productTitle}"
${details ? `Detalhes: "${details}"` : ''}
Cena: "${sceneLocation}", ${sceneTime}. Ação: "${characterAction}" usando "${microphoneType}".

Gere 3 falas em Português do Brasil para vídeos UGC.
REGRA: Cada fala deve ser falada em até 7 segundos (15-20 palavras).
Naturais como uma pessoa real gravando.
Não repita gatilhos mentais.

1. descricao_simples: DEVE começar com "Gente… olha isso aqui, que eu comprei no tiktok shop" + descrição simples atrativa.
2. curiosidade_beneficio: Gatilho mental (escassez, prova social, novidade) + benefício do produto.
3. demonstracao_beneficio: DEVE começar com "O que eu mais gostei foi isso aqui…" + benefício DIFERENTE do anterior.

Responda APENAS com JSON: {"descricao_simples":"...","curiosidade_beneficio":"...","demonstracao_beneficio":"..."}`;

    const response = await fetch('https://api.mistral.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${MISTRAL_KEY}`
      },
      body: JSON.stringify({
        model: 'mistral-small-latest',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        response_format: { type: 'json_object' },
        temperature: 0.9
      })
    });

    if (!response.ok) {
      const err = await response.json();
      throw new Error(err.message || `Mistral error ${response.status}`);
    }

    const data = await response.json();
    const text = data.choices?.[0]?.message?.content || '{}';
    return JSON.parse(text.replace(/```json|```/g, '').trim());
  };

  const generatePrompts = async () => {
    if (!productName.trim()) {
      setError('⚠️ Por favor, insira o nome do produto.');
      return;
    }

    setIsGenerating(true);
    setError(null);
    setPrompts([]);

    try {
      let data;
      if (scriptMode === 'auto') {
        if (selectedModel === 'gemini') {
          data = await callGemini(productName, productDetails);
        } else {
          data = await callMistral(productName, productDetails);
        }
      } else {
        // Manual Mode: use manually entered scripts
        data = {
          descricao_simples: manualScripts.scrollStop,
          curiosidade_beneficio: manualScripts.curiosidade,
          demonstracao_beneficio: manualScripts.demonstracao,
          cta: manualScripts.cta
        };
      }

      const formatContent = (sceneDesc: string, dialogue: string) => {
        return `Descrição da Cena:
Real Brazilian woman recording a vertical smartphone video. 
Location: ${sceneLocation}. 
Time/Lighting: ${sceneTime}. 
Activity: ${characterAction}. 
Audio Setup: Visual of ${microphoneType} on the character.
${sceneDesc}

Dialogue in Brazilian Portuguese (7 seconds):
"${dialogue}"

Constraints:
${SCREEN_CONSTRAINTS.replace('Screen constraints:', '').trim()}

${PRODUCT_FIDELITY}

[BLOCO DE REALISMO]
${BLOCO_DE_REALISMO}`;
      };

      const buildResult = [
        {
          num: '01',
          title: 'Scroll Stop',
          content: formatContent(
            `Real Brazilian woman recording a vertical smartphone video in a home kitchen. She suddenly lifts the product close to the camera as if she just discovered something interesting.\n\nProduct must match the reference image exactly.\nProduct held close to the camera occupying at least 40% of the frame.`,
            data.descricao_simples || ''
          )
        },
        {
          num: '02',
          title: 'Curiosidade',
          content: formatContent(
            `Same woman in the same kitchen environment. She demonstrates a key feature of the product on the counter.\n\nProduct must match the reference image exactly.`,
            data.curiosidade_beneficio || ''
          )
        },
        {
          num: '03',
          title: 'Demonstração',
          content: formatContent(
            `She holds the product close to the camera and rotates it slowly to show details.\n\nProduct must match the reference image exactly.`,
            data.demonstracao_beneficio || ''
          )
        },
        {
          num: '04',
          title: 'Call to Action',
          content: formatContent(
            `Same woman holding the product while pointing toward the corner of the screen.\n\nProduct must match the reference image exactly.`,
            scriptMode === 'auto' ? "Se você quiser o seu também, clica no carrinho laranja aqui no cantinho da tela antes que acabe." : data.cta
          )
        }
      ];

      setPrompts(buildResult);
    } catch (err: any) {
      console.error(err);
      setError(`❌ Erro: ${err.message || 'Falha ao gerar prompts. Tente novamente.'}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const copyToClipboard = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="max-w-6xl mx-auto py-8 px-6 font-rajdhani animate-in fade-in duration-700">
      {/* Header */}
      <header className="text-center mb-12">
        <div className="inline-flex items-center gap-2 bg-brand-purple/10 border border-brand-purple/20 rounded-full px-4 py-1.5 mb-6">
          <span className="w-1.5 h-1.5 rounded-full bg-brand-purple animate-pulse"></span>
          <span className="text-[10px] font-black uppercase tracking-widest text-brand-purple">Umbra Agent · UGC Generator</span>
        </div>
        <h1 className="text-4xl md:text-6xl font-black text-white tracking-tighter uppercase mb-4">
          Umbra <span className="text-brand-purple">Agent</span> UGC <span className="text-yellow-500 text-2xl align-top">V10</span>
        </h1>
        <p className="text-gray-500 text-lg max-w-2xl mx-auto font-medium leading-relaxed">
          Gerador de vídeos UGC para Veo-3. Crie 4 prompts perfeitamente estruturados para manter consistência visual e engajamento.
        </p>
        <div className="w-20 h-1 bg-gradient-to-r from-transparent via-brand-purple to-transparent mx-auto mt-8 opacity-50"></div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_1.8fr] gap-10 items-start">
        {/* Left: Configuration Panel */}
        <aside className="space-y-6">
          <div className="bg-background-mid border border-white/5 rounded-[40px] overflow-hidden shadow-2xl">
            <div className="px-8 py-6 bg-white/5 border-b border-white/5 flex items-center gap-4">
              <div className="w-10 h-10 bg-brand-purple/10 rounded-xl flex items-center justify-center text-brand-purple">
                <Zap className="w-5 h-5" />
              </div>
              <h2 className="text-lg font-black text-white uppercase tracking-tight">Configuração</h2>
            </div>
            
            <div className="p-8 space-y-6">
              {/* Model Toggle */}
              <div>
                <label className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-3 block">Motor de IA</label>
                <div className="flex gap-2 p-1 bg-background-deep rounded-2xl border border-white/5">
                  <button 
                    onClick={() => setSelectedModel('gemini')}
                    className={`flex-1 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${selectedModel === 'gemini' ? 'bg-brand-purple text-white shadow-lg shadow-brand-purple/20' : 'text-gray-600 hover:text-gray-400'}`}
                  >
                    Gemini
                  </button>
                  <button 
                    onClick={() => setSelectedModel('mistral')}
                    className={`flex-1 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${selectedModel === 'mistral' ? 'bg-brand-purple text-white shadow-lg shadow-brand-purple/20' : 'text-gray-600 hover:text-gray-400'}`}
                  >
                    Mistral
                  </button>
                </div>
              </div>

              {/* Script Mode Selector */}
              <div>
                <label className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-3 block italic text-brand-purple">Roteiro / Scripts</label>
                <div className="flex gap-2 p-1 bg-background-deep rounded-2xl border border-white/5">
                  <button 
                    onClick={() => setScriptMode('auto')}
                    className={`flex-1 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all flex items-center justify-center gap-2 ${scriptMode === 'auto' ? 'bg-brand-purple text-white shadow-lg shadow-brand-purple/20' : 'text-gray-600 hover:text-gray-400'}`}
                  >
                    <MessageSquare className="w-3 h-3" />
                    Automático (IA)
                  </button>
                  <button 
                    onClick={() => setScriptMode('manual')}
                    className={`flex-1 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all flex items-center justify-center gap-2 ${scriptMode === 'manual' ? 'bg-brand-purple text-white shadow-lg shadow-brand-purple/20' : 'text-gray-600 hover:text-gray-400'}`}
                  >
                    <Type className="w-3 h-3" />
                    Manual (Eu)
                  </button>
                </div>
              </div>

              {/* Manual Scripts Inputs */}
              {scriptMode === 'manual' && (
                <div className="space-y-4 pt-2 border-t border-white/5 animate-in slide-in-from-top-2 duration-300">
                  <div className="space-y-2">
                    <label className="text-[9px] font-black text-gray-700 uppercase tracking-widest ml-1">Parte 1: Scroll Stop</label>
                    <input 
                      type="text" 
                      value={manualScripts.scrollStop}
                      onChange={(e) => setManualScripts(prev => ({ ...prev, scrollStop: e.target.value }))}
                      className="w-full bg-background-deep border border-white/5 rounded-xl px-4 py-3 text-xs font-medium text-white focus:border-brand-purple/50 outline-none transition-all placeholder:text-gray-800"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[9px] font-black text-gray-700 uppercase tracking-widest ml-1">Parte 2: Curiosidade</label>
                    <input 
                      type="text" 
                      value={manualScripts.curiosidade}
                      onChange={(e) => setManualScripts(prev => ({ ...prev, curiosidade: e.target.value }))}
                      className="w-full bg-background-deep border border-white/5 rounded-xl px-4 py-3 text-xs font-medium text-white focus:border-brand-purple/50 outline-none transition-all placeholder:text-gray-800"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[9px] font-black text-gray-700 uppercase tracking-widest ml-1">Parte 3: Demonstração</label>
                    <input 
                      type="text" 
                      value={manualScripts.demonstracao}
                      onChange={(e) => setManualScripts(prev => ({ ...prev, demonstracao: e.target.value }))}
                      className="w-full bg-background-deep border border-white/5 rounded-xl px-4 py-3 text-xs font-medium text-white focus:border-brand-purple/50 outline-none transition-all placeholder:text-gray-800"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[9px] font-black text-gray-700 uppercase tracking-widest ml-1">Parte 4: Call to Action</label>
                    <input 
                      type="text" 
                      value={manualScripts.cta}
                      onChange={(e) => setManualScripts(prev => ({ ...prev, cta: e.target.value }))}
                      className="w-full bg-background-deep border border-white/5 rounded-xl px-4 py-3 text-xs font-medium text-white focus:border-brand-purple/50 outline-none transition-all placeholder:text-gray-800"
                    />
                  </div>
                </div>
              )}

              {/* Product Name */}
              <div>
                <label className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-3 block">Nome do Produto <span className="text-brand-purple">*</span></label>
                <input 
                  type="text" 
                  value={productName}
                  onChange={(e) => setProductName(e.target.value)}
                  placeholder="Ex: Mini Liquidificador Portátil"
                  className="w-full bg-background-deep border border-white/5 rounded-2xl px-5 py-4 text-sm font-medium text-white focus:border-brand-purple/50 outline-none transition-all placeholder:text-gray-700"
                />
              </div>

              {/* Product Details */}
              <div>
                <label className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-3 block">Detalhes / Benefícios <span className="text-gray-700">(Opcional)</span></label>
                <textarea 
                  value={productDetails}
                  onChange={(e) => setProductDetails(e.target.value)}
                  placeholder="Ex: Bateria dura 1 semana, tritura gelo, fácil de lavar..."
                  rows={4}
                  className="w-full bg-background-deep border border-white/5 rounded-3xl px-5 py-4 text-sm font-medium text-white focus:border-brand-purple/50 outline-none transition-all placeholder:text-gray-700 resize-none"
                />
              </div>

              {/* Scene Configuration */}
              <div className="space-y-4 pt-4 border-t border-white/5">
                <h3 className="text-[10px] font-black text-brand-purple uppercase tracking-widest flex items-center gap-2">
                  <Activity className="w-3 h-3" />
                  Detalhes da Cena
                </h3>
                
                <div>
                  <label className="text-[9px] font-black text-gray-500 uppercase tracking-widest mb-2 block flex items-center gap-2">
                    <MapPin className="w-3 h-3" />
                    Onde a cena se passa?
                  </label>
                  <input 
                    type="text" 
                    value={sceneLocation}
                    onChange={(e) => setSceneLocation(e.target.value)}
                    placeholder="Ex: Cozinha moderna, escritório, rua arborizada..."
                    className="w-full bg-background-deep border border-white/5 rounded-xl px-4 py-3 text-xs font-medium text-white focus:border-brand-purple/50 outline-none transition-all"
                  />
                </div>

                <div>
                  <label className="text-[9px] font-black text-gray-500 uppercase tracking-widest mb-2 block flex items-center gap-2">
                    <Clock className="w-3 h-3" />
                    Que horas é a cena?
                  </label>
                  <input 
                    type="text" 
                    value={sceneTime}
                    onChange={(e) => setSceneTime(e.target.value)}
                    placeholder="Ex: Manhã ensolarada, luz suave de fim de tarde..."
                    className="w-full bg-background-deep border border-white/5 rounded-xl px-4 py-3 text-xs font-medium text-white focus:border-brand-purple/50 outline-none transition-all"
                  />
                </div>

                <div>
                  <label className="text-[9px] font-black text-gray-500 uppercase tracking-widest mb-2 block flex items-center gap-2">
                    <Activity className="w-3 h-3" />
                    O que o personagem faz?
                  </label>
                  <input 
                    type="text" 
                    value={characterAction}
                    onChange={(e) => setCharacterAction(e.target.value)}
                    placeholder="Ex: Mostrando o produto para a câmera..."
                    className="w-full bg-background-deep border border-white/5 rounded-xl px-4 py-3 text-xs font-medium text-white focus:border-brand-purple/50 outline-none transition-all"
                  />
                </div>

                <div>
                  <label className="text-[9px] font-black text-gray-500 uppercase tracking-widest mb-2 block flex items-center gap-2">
                    <Mic className="w-3 h-3" />
                    Tipo de Microfone
                  </label>
                  <select 
                    value={microphoneType}
                    onChange={(e) => setMicrophoneType(e.target.value)}
                    className="w-full bg-background-deep border border-white/5 rounded-xl px-4 py-3 text-xs font-medium text-white focus:border-brand-purple/50 outline-none transition-all appearance-none cursor-pointer"
                  >
                    <option value="lapela sem fio ou com fio">Lapela sem fio ou com fio</option>
                    <option value="microfone handheld padrão">Microfone handheld padrão</option>
                    <option value="microfone com cubo de reportagem">Microfone com cubo de reportagem</option>
                    <option value="microfone simples de rua">Microfone simples de rua</option>
                    <option value="microfone escondido">Microfone escondido</option>
                  </select>
                </div>
              </div>

              {/* Image Upload */}
              <div>
                <label className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-3 block">Imagem de Referência <span className="text-gray-700">(Opcional)</span></label>
                {!imageBase64 ? (
                  <div 
                    onClick={() => fileInputRef.current?.click()}
                    className="border-2 border-dashed border-white/5 bg-background-deep hover:bg-white/5 hover:border-brand-purple/30 rounded-3xl p-8 text-center cursor-pointer transition-all group"
                  >
                    <Upload className="w-8 h-8 text-gray-700 group-hover:text-brand-purple mx-auto mb-4" />
                    <p className="text-xs font-bold text-gray-600 uppercase tracking-tight">Clique para carregar</p>
                    <span className="text-[9px] text-gray-800 uppercase mt-1 block tracking-widest">JPG, PNG ATÉ 5MB</span>
                    <input 
                      type="file" 
                      ref={fileInputRef}
                      onChange={handleImageUpload}
                      accept="image/*"
                      className="hidden"
                    />
                  </div>
                ) : (
                  <div className="relative rounded-3xl overflow-hidden border border-white/5 shadow-2xl group">
                    <img src={imageBase64} alt="Preview" className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-700" />
                    <button 
                      onClick={removeImage}
                      className="absolute top-4 right-4 p-2 bg-red-500/80 text-white rounded-xl hover:bg-red-500 transition-all shadow-xl"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                )}
              </div>

              {/* Error Message */}
              {error && (
                <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-2xl flex items-center gap-3 text-red-400 text-xs font-medium animate-in fade-in zoom-in duration-300">
                  <AlertCircle className="w-4 h-4 shrink-0" />
                  {error}
                </div>
              )}

              {/* Generate Button */}
              <button 
                onClick={generatePrompts}
                disabled={isGenerating}
                className={`w-full py-4 rounded-[20px] font-black text-xs uppercase tracking-[0.2em] shadow-2xl transition-all flex items-center justify-center gap-3 ${isGenerating ? 'bg-gray-800 text-gray-600 cursor-not-allowed' : 'bg-brand-purple text-white shadow-brand-purple/30 hover:brightness-110 active:scale-[0.98]'}`}
              >
                {isGenerating ? (
                  <>
                    <div className="w-4 h-4 border-2 border-gray-600 border-t-white rounded-full animate-spin"></div>
                    Gerando Prompts...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    Gerar Prompts para Veo-3
                  </>
                )}
              </button>
            </div>
          </div>

          <div className="p-6 bg-brand-purple/5 border border-brand-purple/10 rounded-3xl flex gap-4 items-start">
            <Info className="w-5 h-5 text-brand-purple shrink-0 mt-0.5" />
            <p className="text-[11px] font-medium text-gray-500 leading-relaxed uppercase">
              As ferramentas de API estão configuradas com limites profissionais para garantir a melhor performance em seus roteiros UGC.
            </p>
          </div>
        </aside>

        {/* Right: Output Panel */}
        <main>
          {prompts.length === 0 ? (
            <div className="bg-background-mid border border-white/5 border-dashed rounded-[48px] p-20 text-center flex flex-col items-center justify-center min-h-[600px] opacity-40 shadow-2xl">
              <div className="w-20 h-20 bg-white/5 rounded-[32px] flex items-center justify-center mb-8">
                <Video className="w-10 h-10 text-gray-700" />
              </div>
              <h3 className="text-2xl font-black text-white uppercase tracking-tighter mb-4">Nenhum prompt gerado ainda</h3>
              <p className="text-gray-500 max-w-sm mx-auto text-sm leading-relaxed font-medium uppercase">
                Preencha os dados do produto ao lado e clique em gerar para criar a sequência de 4 vídeos UGC.
              </p>
            </div>
          ) : (
            <div className="space-y-6 animate-in slide-in-from-bottom-8 duration-700">
              {prompts.map((p, i) => (
                <div key={i} className="bg-background-mid border border-white/5 rounded-[40px] overflow-hidden shadow-2xl group hover:border-brand-purple/30 transition-all">
                  <div className="px-8 py-5 bg-white/5 border-b border-white/5 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 bg-brand-purple/10 rounded-xl flex items-center justify-center text-brand-purple font-black text-xs">
                        {p.num}
                      </div>
                      <h4 className="text-sm font-black text-white uppercase tracking-widest">{p.title}</h4>
                    </div>
                    <button 
                      onClick={() => copyToClipboard(p.content, i)}
                      className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${copiedIndex === i ? 'bg-green-500 text-white' : 'bg-background-deep text-gray-500 hover:text-white hover:bg-brand-purple/20 border border-white/5'}`}
                    >
                      {copiedIndex === i ? (
                        <>
                          <CheckCircle2 className="w-3 h-3" />
                          Copiado!
                        </>
                      ) : (
                        <>
                          <Copy className="w-3 h-3" />
                          Copiar
                        </>
                      )}
                    </button>
                  </div>
                  <div className="p-8">
                    <pre className="text-xs font-medium font-mono text-gray-400 leading-relaxed whitespace-pre-wrap break-words bg-background-deep/50 p-6 rounded-3xl border border-white/5 group-hover:border-brand-purple/10 transition-all">
                      {p.content}
                    </pre>
                  </div>
                </div>
              ))}
            </div>
          )}
        </main>
      </div>

      <footer className="mt-16 text-center border-t border-white/5 pt-10 text-[10px] font-black text-gray-600 uppercase tracking-[0.2em]">
        UMBRA AGENT UGC V10 · POWERED BY GEMINI & MISTRAL · FOR VEO-3
      </footer>

      <style>{`
        .no-scrollbar::-webkit-scrollbar { display: none; }
        .no-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }
      `}</style>
    </div>
  );
};

export default UmbraAgentUGCTool;
